#!/bin/sh

BRANCH_PATTERN="(feat|bug|test)/"

while read oldrev newrev refname; do
    if ! [[ $refname =~ ^refs/heads/$BRANCH_PATTERN ]]; then
        echo "ERROR: Branch name \"$refname\" does not match the required pattern (feat/, bug/, or test/)."
        exit 1
    fi
done