name: course website vercel deployment
env: 
    VERCEL_ORG_ID: team_aGHRiTK1Opxexh8TE2hiA7cH
    VERCEL_PROJECT_ID: prj_Asc8SWAoZW6dZJOyOIfBBKAV4Cv0
    VERCEL_TOKEN: xvdfFswJmBpl1PTefRAdihTj
on:
  push:
    branches:
      - dev

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
         node-version: 20
         cache: yarn
    - name: Pull Vercel Environment Information
      run: vercel pull --yes --environment=production --token=xvdfFswJmBpl1PTefRAdihTj
    - name: Build Project Artifacts
      run: vercel build --prod --token=xvdfFswJmBpl1PTefRAdihTj
    - name: Deploy Project Artifacts to Vercel
      run: vercel deploy --prebuilt --prod --token=xvdfFswJmBpl1PTefRAdihTj
